title: Jinesh Codes
description: Jinesh's coding blog. Interview experiences, coding guides and much more.

url: https://jineshcodes.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: jineshcodes
  instagram: jinesh.codes
  email: jinesh.codes@gmail.com
  linkedin: jineshshah11

google_analytics: "G-9H73HF5CNB"

disqus:
    shortname: jinesh-codes
